{
 "title": "FRITZ!Box Router Status",
 "description": "Monitor FRITZ!Box routers",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "measurement", "label": "InfluxDB measurement", "query": "${VAR_MEASUREMENT}" },
   { "name": "timezone", "label": "specify your timezone", "query": "${VAR_TIMEZONE}" },
   {
    "name": "boxtag",
    "label": "FritzBox",
    "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"$measurement\" and r._field == \"linkuptime\")\n  |> keyValues(keyColumns: [\"box\"])\n  |> group()\n  |> keep(columns: [\"box\"])\n  |> distinct(column: \"box\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Current UP/DOWN",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "finalMap = (tables=<-) => tables\n  |> map(fn: (r) =>  ({\n        r with _value:\n          if r._field =~ /.*rate$/ then r._value * 8.0\n          else if r._field =~ /.*dsl_sync_max$/ then r._value * 1000.0\n          else r._value,\n        _field:\n          if r._field == \"sendrate\" then \"UP\"\n          else if r._field == \"receiverate\" then \"DOWN\"\n          else if r._field == \"downstreammax\" then \"DOWN netto Max\"\n          else if r._field == \"downstreamphysicalmax\" then \"DOWN Physical Max\"\n          else if r._field == \"downstream_dsl_sync_max\" then \"DOWN DSL Sync\"\n          else if r._field == \"upstreammax\" then \"UP netto Max\"\n          else if r._field == \"upstreamphysicalmax\" then \"UP Physical Max\"\n          else if r._field == \"upstream_dsl_sync_max\" then \"UP DSL Sync\"\n          else r._field\n        })\n      )\n\nfrom(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r.box == \"${boxtag}\" and\n    (\n        r._field == \"sendrate\" or\n        r._field == \"receiverate\" or\n        r._field == \"downstreammax\" or\n        r._field == \"downstream_dsl_sync_max\" or\n        r._field == \"downstreamphysicalmax\" or\n        r._field == \"upstreammax\" or\n        r._field == \"upstream_dsl_sync_max\" or\n        r._field == \"upstreamphysicalmax\"\n    )\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n  |> sort(columns: [\"_time\"], desc: false)\n  |> finalMap()\n",
       "select": [
        [
         { "params": [ "sendrate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "UP" ], "type": "alias" }
        ],
        [
         { "params": [ "receiverate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "DOWN" ], "type": "alias" }
        ],
        [
         { "params": [ "downstreammax" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "DOWN netto Max" ], "type": "alias" }
        ],
        [
         { "params": [ "downstream_dsl_sync_max" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*1000" ], "type": "math" },
         { "params": [ "DOWN DSL Sync" ], "type": "alias" }
        ],
        [
         { "params": [ "downstreamphysicalmax" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "DOWN Physical Max" ], "type": "alias" }
        ],
        [
         { "params": [ "upstreammax" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "UP netto Max" ], "type": "alias" }
        ],
        [
         { "params": [ "upstream_dsl_sync_max" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*1000" ], "type": "math" },
         { "params": [ "UP DSL Sync" ], "type": "alias" }
        ],
        [
         { "params": [ "upstreamphysicalmax" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "UP Physical Max" ], "type": "alias" }
        ],
        [
         { "params": [ "crc_errors" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "$__interval" ], "type": "non_negative_derivative" },
         { "params": [ "CRC Errors" ], "type": "alias" }
        ],
        [
         { "params": [ "errored_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "$__interval" ], "type": "non_negative_derivative" },
         { "params": [ "Errored Seconds" ], "type": "alias" }
        ],
        [
         { "params": [ "severely_errored_seconds" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "$__interval" ], "type": "non_negative_derivative" },
         { "params": [ "Severely Errored Seconds" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "query": "finalMap = (tables=<-) => tables\n  |> map(fn: (r) =>  ({\n        r with _field:\n          if r._field == \"crc_errors\" then \"CRC Errors\"\n          else if r._field == \"errored_seconds\" then \"Errored Seconds\"\n          else if r._field == \"severely_errored_seconds\" then \"Severely Errored Seconds\"\n          else r._field\n        })\n      )\n\nfrom(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"$boxtag\" and \n    (\n        r._field == \"crc_errors\" or\n        r._field == \"errored_seconds\" or\n        r._field == \"severely_errored_seconds\"\n    )\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> derivative(unit: v.windowPeriod, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\")\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n  |> sort(columns: [\"_time\"], desc: false)\n  |> finalMap()"
      }
     ]
    },
    {
     "title": "Last 5 Log Entries",
     "type": "logs",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "limit": "5",
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"log_entry\" )\n  |> limit(n:5, offset: 0)\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n  |> sort(columns: [\"_time\"], desc: true)\n",
       "select": [
        [
         { "params": [ "log_entry" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "Update",
     "type": "stat",
     "description": "Is there a Fritz!OS update available",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r[\"_field\"] == \"upgrade_available\" and r.box == \"${boxtag}\")\n  |> last()\n  |> keep(columns: [\"_value\"])",
       "select": [
        [
         { "params": [ "upgrade_available" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "DSL Link Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 2, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r[\"_field\"] == \"linkuptime\" and r.box == \"${boxtag}\")\n  |> last()\n  |> keep(columns: [\"_value\"])",
       "select": [
        [
         { "params": [ "linkuptime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "Current Download",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r.box == \"${boxtag}\" and\n    (\n        r._field == \"receiverate\" or\n        r._field == \"downstreammax\"\n    )\n  )\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n  |> last()\n  |> map(fn: (r) =>  ({\n    r with _value:\n      if r._field == \"receiverate\" then r._value * 8\n      else r._value,\n    })\n  )\n",
       "select": [
        [
         { "params": [ "receiverate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "current" ], "type": "alias" }
        ],
        [
         { "params": [ "downstreammax" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Current Upload",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r.box == \"${boxtag}\" and\n    (\n        r._field == \"sendrate\" or\n        r._field == \"upstreammax\"\n    )\n  )\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n  |> last()\n  |> map(fn: (r) =>  ({\n    r with _value:\n      if r._field == \"sendrate\" then r._value * 8\n      else r._value,\n    })\n  )\n",
       "select": [
        [
         { "params": [ "sendrate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "current" ], "type": "alias" }
        ],
        [
         { "params": [ "upstreammax" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "max" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Temp",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r[\"_field\"] == \"cpu_temp\" and r.box == \"${boxtag}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_value\"])",
       "select": [
        [
         { "params": [ "cpu_temp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 14, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"cpu_utilization\" )\n  |> last()\n  |> keep(columns: [\"_value\"])",
       "select": [
        [
         { "params": [ "cpu_utilization" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM Utilization",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "// SELECT last(\"ram_usage_fixed\") + last(\"ram_usage_dynamic\") FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/) AND $timeFilter GROUP BY time($__interval) fill(linear)\nfrom(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r.box == \"${boxtag}\" and\n    (\n      r._field == \"ram_usage_fixed\" or r._field == \"ram_usage_dynamic\"\n    )\n  )\n  |> last()\n  |> keep(columns: [\"_value\"])",
       "select": [
        [
         { "params": [ "ram_usage_fixed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "Last 24h Upload",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "fritzbox_value",
       "query": "import \"timezone\"\noption location = timezone.location(name: \"${timezone}\")\nfrom(bucket: v.defaultBucket)\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"totalbytessent\" )\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> cumulativeSum(columns: [\"_value\"])\n  |> aggregateWindow(every: 15m, fn: last, createEmpty: false)\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
       ]
      }
     ]
    },
    {
     "title": "Last 24h Download",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "fritzbox_value",
       "query": "import \"timezone\"\noption location = timezone.location(name: \"${timezone}\")\nfrom(bucket: v.defaultBucket)\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"totalbytesreceived\" )\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> cumulativeSum(columns: [\"_value\"])\n  |> aggregateWindow(every: 15m, fn: last, createEmpty: false)\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
       ]
      }
     ]
    },
    {
     "title": "Active hosts",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r[\"_field\"] == \"num_active_host\" and r.box == \"${boxtag}\")\n  |> last()\n  |> keep(columns: [\"_value\"])",
       "select": [
        [
         { "params": [ "num_active_host" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "System Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 2, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\" and r[\"_field\"] == \"systemuptime\" and r.box == \"${boxtag}\")\n  |> last()\n  |> keep(columns: [\"_value\"])",
       "select": [
        [
         { "params": [ "systemuptime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "import \"timezone\"\noption location = timezone.location(name: \"${timezone}\")\nfrom(bucket: v.defaultBucket)\n  |> range(start: -7d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and \n    (\n      r._field == \"totalbytesreceived\" or\n      r._field == \"totalbytessent\"\n    )\n  )\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> fill(column: \"_value\", usePrevious: true)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n  |> sort(columns: [\"_time\"], desc: false)\n  |> truncateTimeColumn(unit: 1h)\n  |> timeShift(duration: -1d, columns: [\"_time\"])\n\n"
      }
     ]
    },
    {
     "title": "Current Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Download",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "fritzbox_value",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and \n    (\n      r._field == \"totalbytesreceived\" or \n      r._field == \"totalbytessent\"\n    )\n  )\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> cumulativeSum(columns: [\"_value\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> drop(columns: [\"box\", \"_measurement\"])\n  |> truncateTimeColumn(unit: 1h)\n  |> timeShift(duration: -1h)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
       ],
       "target": "alias(summarize(nonNegativeDerivative(collectd.squirrel.fritzbox.bytes-totalbytesreceived, 0), '1h', 'sum'), 'download')"
      }
     ]
    },
    {
     "title": "Daily Traffic",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Download",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" }
       ],
       "measurement": "fritzbox_value",
       "query": "import \"timezone\"\noption location = timezone.location(name: \"${timezone}\")\nfrom(bucket: v.defaultBucket)\n  |> range(start: -7d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and \n    (\n      r._field == \"totalbytesreceived\" or\n      r._field == \"totalbytessent\"\n    )\n  )\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> fill(column: \"_value\", usePrevious: true)\n  |> cumulativeSum(columns: [\"_value\"])\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n  |> timeShift(duration: -1ns, columns: [\"_time\"])\n  |> difference(nonNegative: true, columns: [\"_value\"])\n  |> drop(columns: [\"box\", \"_measurement\"])\n  |> truncateTimeColumn(unit: 1m)\n  |> timeShift(duration: 1ns, columns: [\"_time\"])",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
       ]
      }
     ]
    },
    {
     "title": "Total Upload since connection",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"totalbytessent\" )\n  |> aggregateWindow(every: 15m, fn: last, createEmpty: false)",
       "select": [
        [
         { "params": [ "totalbytessent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Download since connection",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"totalbytesreceived\" )\n  |> aggregateWindow(every: 15m, fn: last, createEmpty: false)\n",
       "select": [
        [
         { "params": [ "totalbytesreceived" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "WLAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "WLAN Clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field =~ /^wlan._associations$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n\n",
       "select": [
        [
         { "params": [ "wlan1_associations" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "2.4 GHz Clients" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_associations" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "5 GHz Clients" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_associations" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Guest Clients" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "WLAN Channel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field =~ /^wlan._channel$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n",
       "select": [
        [
         { "params": [ "wlan1_channel" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "2.4 GHz" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_channel" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "5 GHz" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_channel" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Guest" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "WLAN Info",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "alias": "2.4 GHz Status",
       "limit": "1",
       "measurement": "/^$measurement$/",
       "query": "finalMap = (tables=<-) => tables\n  |> map(fn: (r) =>  ({\n        r with _field:\n          if r._field =~ /.*ssid/ then \"Name\"\n          else if r._field =~ /.*status/ then \"Status\"\n          else if r._field =~ /.*standard/ then \"Standard\"\n          else if r._field =~ /.*channel/ then \"Channel\"\n          else if r._field =~ /.*associations/ then \"Clients\"\n          else r._field\n        })\n      )\n\n\nfrom(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field =~ /^wlan1.*$/)\n  |> last()\n  |> toString()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n  |> truncateTimeColumn(unit: 1h)\n  |> finalMap()\n",
       "select": [
        [
         { "params": [ "wlan1_ssid" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Name" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan1_status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Status" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan1_802.11_standard" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Standard" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan1_channel" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Channel" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan1_associations" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Clients" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "alias": "2.4 GHz Status",
       "limit": "1",
       "measurement": "/^$measurement$/",
       "query": "finalMap = (tables=<-) => tables\n  |> map(fn: (r) =>  ({\n        r with _field:\n          if r._field =~ /.*ssid/ then \"Name\"\n          else if r._field =~ /.*status/ then \"Status\"\n          else if r._field =~ /.*standard/ then \"Standard\"\n          else if r._field =~ /.*channel/ then \"Channel\"\n          else if r._field =~ /.*associations/ then \"Clients\"\n          else r._field\n        })\n      )\n\n\nfrom(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field =~ /^wlan2.*$/)\n  |> last()\n  |> toString()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n  |> truncateTimeColumn(unit: 1h)\n  |> finalMap()",
       "select": [
        [
         { "params": [ "wlan2_ssid" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Name" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Status" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_802.11_standard" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Standard" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_channel" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Channel" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_associations" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Clients" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "alias": "2.4 GHz Status",
       "limit": "1",
       "measurement": "/^$measurement$/",
       "query": "finalMap = (tables=<-) => tables\n  |> map(fn: (r) =>  ({\n        r with _field:\n          if r._field =~ /.*ssid/ then \"Name\"\n          else if r._field =~ /.*status/ then \"Status\"\n          else if r._field =~ /.*standard/ then \"Standard\"\n          else if r._field =~ /.*channel/ then \"Channel\"\n          else if r._field =~ /.*associations/ then \"Clients\"\n          else r._field\n        })\n      )\n\n\nfrom(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field =~ /^wlan3.*$/)\n  |> last()\n  |> toString()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n  |> truncateTimeColumn(unit: 1h)\n  |> finalMap()\n",
       "select": [
        [
         { "params": [ "wlan3_ssid" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Name" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Status" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_802.11_standard" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Standard" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_channel" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Channel" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_associations" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Clients" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "System Infos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "CPU Utilization",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"cpu_utilization\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n\n",
       "select": [
        [
         { "params": [ "cpu_utilization" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"ram_usage_fixed\" )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n",
       "select": [
        [
         { "params": [ "ram_usage_fixed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Fixed" ], "type": "alias" }
        ],
        [
         { "params": [ "ram_usage_dynamic" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Dynamic" ], "type": "alias" }
        ],
        [
         { "params": [ "ram_usage_free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Free" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"ram_usage_dynamic\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n"
      },
      {
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"ram_usage_free\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n"
      }
     ]
    },
    {
     "title": "CPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "CPU Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"cpu_temp\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])\n\n",
       "select": [
        [
         { "params": [ "cpu_temp" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "System Energy Consumption",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"energy_consumption\")\n  |> last()",
       "select": [
        [
         { "params": [ "energy_consumption" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "FritzBox Info",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and\n    (\n      r._field == \"external_ip\" or\n      r._field == \"external_ipv6\" or\n      r._field == \"model\" or\n      r._field == \"serialnumber\" or\n      r._field == \"softwareversion\" or\n      r._field == \"last_auth_error\" or\n      r._field == \"myfritz_host_name\"\n    ) \n  )\n  |> last()\n  |> toString()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) =>  ({\n        r with _field:\n          if r._field == \"external_ip\" then \"IPv4\"\n          else if r._field == \"external_ipv6\" then \"IPv6\"\n          else if r._field == \"model\" then \"Model\"\n          else if r._field == \"serialnumber\" then \"Serial\"\n          else if r._field == \"softwareversion\" then \"SW Version\"\n          else if r._field == \"last_auth_error\" then \"Last Auth Error\"\n          else if r._field == \"myfritz_host_name\" then \"MyFritz Hostname\"\n          else r._field\n        })\n      )\n",
       "select": [
        [
         { "params": [ "external_ip" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "IPv4" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "Connection Info",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and\n    (\n      r._field == \"physicallinktype\" or\n      r._field == \"dsl_line_length\" or\n      r._field == \"dsl_dslam_vendor\" or\n      r._field == \"dsl_dslam_sw_version\" or\n      r._field == \"dsl_line_mode\" or\n      r._field == \"cable_cmts_vendor\" or\n      r._field == \"cable_line_mode\" or\n      r._field == \"cable_modem_version\" or\n      r._field == \"cable_num_ds_channels\" or\n      r._field == \"cable_num_us_channels\" or\n      r._field == \"connection_status\" or\n      r._field == \"last_connection_error\" or\n      r._field == \"remote_pop\"\n    ) \n  )\n  |> last()\n  |> toString()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) =>  ({\n        r with _field:\n          if r._field == \"physicallinktype\" then \"Link Type\"\n          else if r._field == \"dsl_line_length\" then \"DSL Line Length\"\n          else if r._field == \"dsl_dslam_vendor\" then \"DSL DSLAM Vendor\"\n          else if r._field == \"dsl_dslam_sw_version\" then \"DSL Model Version\"\n          else if r._field == \"dsl_line_mode\" then \"DSL Line Mode\"\n          else if r._field == \"cable_cmts_vendor\" then \"Cable Vendor\"\n          else if r._field == \"cable_line_mode\" then \"Cable Line Mode\"\n          else if r._field == \"cable_modem_version\" then \"Cable Modem Version\"\n          else if r._field == \"cable_num_ds_channels\" then \"Cable Downstream Channels\"\n          else if r._field == \"cable_num_us_channels\" then \"Cable Upstream Channels\"\n          else if r._field == \"connection_status\" then \"Connection Status\"\n          else if r._field == \"last_connection_error\" then \"Last Connection Error\"\n          else if r._field == \"remote_pop\" then \"Remote Pop\"\n          else r._field\n        })\n      )\n",
       "select": [
        [
         { "params": [ "physicallinktype" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Link Type" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "VPN and DynDNS Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active VPN User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 5 },
     "targets": [
      {
       "alias": "Num Users",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field == \"vpn_user_num_active\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\"])",
       "select": [
        [
         { "params": [ "vpn_user_num_active" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "VPN Infos",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 5 },
     "targets": [
      {
       "alias": "MyFritz Hostname",
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and\n    (\n      r._field == \"myfritz_host_name\" or\n      r._field == \"vpn_type\" or\n      r._field == \"vpn_user_num_active\"\n    ) \n  )\n  |> last()\n  |> toString()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) =>  ({\n        r with _field:\n          if r._field == \"myfritz_host_name\" then \"MyFritz Hostname\"\n          else if r._field == \"vpn_type\" then \"VPN Type\"\n          else if r._field == \"vpn_user_num_active\" then \"VPN User Active\"\n          else r._field\n        })\n      )\n",
       "select": [
        [
         { "params": [ "myfritz_host_name" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "DynDNS Info",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
     "targets": [
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and\n    (\n      r._field == \"ddns_domain\" or\n      r._field == \"ddns_enabled\" or\n      r._field == \"ddns_mode\" or\n      r._field == \"ddns_provider_name\" or\n      r._field == \"ddns_status_ipv4\" or\n      r._field == \"ddns_status_ipv6\"\n    ) \n  )\n  |> last()\n  |> toString()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\", \"_time\"])\n  |> map(fn: (r) =>  ({\n        r with _field:\n          if r._field == \"ddns_domain\" then \"Domain\"\n          else if r._field == \"ddns_enabled\" then \"Enabled\"\n          else if r._field == \"ddns_mode\" then \"Mode\"\n          else if r._field == \"ddns_provider_name\" then \"Provider\"\n          else if r._field == \"ddns_status_ipv4\" then \"Status IPv4\"\n          else if r._field == \"ddns_status_ipv6\" then \"Status IPv6\"\n          else r._field\n        })\n      )\n",
       "select": [
        [
         { "params": [ "ddns_domain" ], "type": "field" },
         { "params": [ "Domain" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_enabled" ], "type": "field" },
         { "params": [ "Enabled" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_mode" ], "type": "field" },
         { "params": [ "Mode" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_provider_name" ], "type": "field" },
         { "params": [ "Provider" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_status_ipv4" ], "type": "field" },
         { "params": [ "Status IPv4" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_status_ipv6" ], "type": "field" },
         { "params": [ "Status IPv6" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "VPN User Overview",
     "type": "table",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 13 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "limit": "1",
       "measurement": "/^$measurement$/",
       "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and\n    (\n      r._field == \"vpn_user_active\" or\n      r._field == \"vpn_user_connected\" or\n      r._field == \"vpn_user_virtual_address\" or\n      r._field == \"vpn_user_remote_address\"\n    ) \n  )\n  |> last()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\", \"_time\"])\n\n",
       "select": [
        [
         { "params": [ "vpn_user_active" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Active" ], "type": "alias" }
        ],
        [
         { "params": [ "vpn_user_connected" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Connected" ], "type": "alias" }
        ],
        [
         { "params": [ "vpn_user_virtual_address" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Virtual Address" ], "type": "alias" }
        ],
        [
         { "params": [ "vpn_user_remote_address" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Remote Address" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "Active Hosts",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "uid" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field =~ /active_hosts_.*/ )\n  |> last()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\", \"_time\"])\n",
     "select": [
      [
       { "params": [ "active_hosts_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Name" ], "type": "alias" }
      ],
      [
       { "params": [ "active_hosts_mac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Mac" ], "type": "alias" }
      ],
      [
       { "params": [ "active_hosts_type" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Type" ], "type": "alias" }
      ],
      [
       { "params": [ "active_hosts_port" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Port" ], "type": "alias" }
      ],
      [
       { "params": [ "active_hosts_ipv4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IPv4" ], "type": "alias" }
      ],
      [
       { "params": [ "active_hosts_ipv4_last_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "Last seen" ], "type": "alias" }
      ],
      [
       { "params": [ "active_hosts_additional_text" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Info" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
     ]
    }
   ]
  },
  {
   "title": "Passive Hosts",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "uid" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"${measurement}\" and r.box == \"${boxtag}\" and r._field =~ /passive_hosts_.*/ )\n  |> last()\n  |> drop(columns: [\"box\", \"_measurement\", \"_start\", \"_stop\", \"_time\"])\n",
     "select": [
      [
       { "params": [ "passive_hosts_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Name" ], "type": "alias" }
      ],
      [
       { "params": [ "passive_hosts_mac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Mac" ], "type": "alias" }
      ],
      [
       { "params": [ "passive_hosts_port" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Port" ], "type": "alias" }
      ],
      [
       { "params": [ "passive_hosts_ipv4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "IPv4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
     ]
    }
   ]
  }
 ]
}