{
 "title": "FRITZ!Box Router Status",
 "description": "Monitor FRITZ!Box routers",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "measurement", "label": "InfluxDB measurement", "query": "${VAR_MEASUREMENT}" },
   {
    "name": "boxtag",
    "label": "FritzBox",
    "query": "SHOW TAG VALUES FROM $measurement WITH KEY=box"
   },
   {
    "name": "timezone",
    "query": "SELECT last(\"fritzinfluxdb_setting_timezone\") FROM /^$measurement$/ WHERE \"box\" =~ /^$boxtag$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current UP/DOWN",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "sendrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "UP" ], "type": "alias" }
      ],
      [
       { "params": [ "receiverate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "DOWN" ], "type": "alias" }
      ],
      [
       { "params": [ "downstreammax" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DOWN netto Max" ], "type": "alias" }
      ],
      [
       { "params": [ "downstream_dsl_sync_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "DOWN DSL Sync" ], "type": "alias" }
      ],
      [
       { "params": [ "downstreamphysicalmax" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DOWN Physical Max" ], "type": "alias" }
      ],
      [
       { "params": [ "upstreammax" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "UP netto Max" ], "type": "alias" }
      ],
      [
       { "params": [ "upstream_dsl_sync_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "UP DSL Sync" ], "type": "alias" }
      ],
      [
       { "params": [ "upstreamphysicalmax" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "UP Physical Max" ], "type": "alias" }
      ],
      [
       { "params": [ "crc_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" },
       { "params": [ "CRC Errors" ], "type": "alias" }
      ],
      [
       { "params": [ "errored_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" },
       { "params": [ "Errored Seconds" ], "type": "alias" }
      ],
      [
       { "params": [ "severely_errored_seconds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$__interval" ], "type": "non_negative_derivative" },
       { "params": [ "Severely Errored Seconds" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
     ]
    }
   ]
  },
  {
   "title": "Last 5 Log Entries",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "limit": "5",
     "measurement": "/^$measurement$/",
     "query": "SELECT \"log_entry\" FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/ AND \"log_type\" = 'Internet connection') AND $timeFilter GROUP BY \"log_type\"",
     "select": [
      [
       { "params": [ "log_entry" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" },
      { "condition": "AND", "key": "log_type", "operator": "!=", "value": "FritzInfluxDB" }
     ]
    }
   ]
  },
  {
   "title": "Update",
   "type": "stat",
   "description": "Is there a Fritz!OS update available",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"upgrade_available\") FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/)",
     "select": [
      [
       { "params": [ "upgrade_available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DSL Link Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$measurement$/",
     "query": "SELECT \"linkuptime\" FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/)",
     "select": [
      [
       { "params": [ "linkuptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Download",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"receiverate\")*8 AS \"current\", last(\"downstreammax\") AS \"max\" FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/)",
     "select": [
      [
       { "params": [ "receiverate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "current" ], "type": "alias" }
      ],
      [
       { "params": [ "downstreammax" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"sendrate\")*8 AS \"current\", last(\"upstreammax\") AS \"max\" FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/)",
     "select": [
      [
       { "params": [ "sendrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "current" ], "type": "alias" }
      ],
      [
       { "params": [ "upstreammax" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "cpu_temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "cpu_utilization" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"ram_usage_fixed\") + last(\"ram_usage_dynamic\") FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "ram_usage_fixed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
     ]
    }
   ]
  },
  {
   "title": "Last 24h Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"totalbytessent\"))) FROM /^$measurement$/  WHERE (\"box\" =~ /^$boxtag$/) AND $timeFilter  GROUP BY time($__interval) tz(${timezone:singlequote})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "Last 24h Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox_value",
     "query": "SELECT cumulative_sum(non_negative_difference(last(\"totalbytesreceived\"))) FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/) AND  $timeFilter GROUP BY time($__interval) tz(${timezone:singlequote})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
     ]
    }
   ]
  },
  {
   "title": "Active hosts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"active_host\"::field), \"port\"::tag, \"ipv4_last_used\"::tag::integer  FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/) AND $timeFilter GROUP BY time($interval), \"name\", \"mac\", \"port\"",
     "select": [
      [
       { "params": [ "num_active_host" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
     ]
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"systemuptime\") FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/)",
     "select": [
      [
       { "params": [ "systemuptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Daily Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Download",
       "groupBy": [
        { "params": [ "24h" ], "type": "time" }
       ],
       "measurement": "fritzbox_value",
       "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(\"totalbytesreceived\"))) FROM /^$measurement$/ WHERE  (\"box\" =~ /^$boxtag$/) AND $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time(1d) tz(${timezone:singlequote})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
       ]
      },
      {
       "alias": "Upload",
       "groupBy": [
        { "params": [ "24h" ], "type": "time" }
       ],
       "measurement": "fritzbox_value",
       "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(totalbytessent))) FROM /^$measurement$/ WHERE  (\"box\" =~ /^$boxtag$/) AND $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time(1d) tz(${timezone:singlequote})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
       ]
      }
     ]
    },
    {
     "title": "Current Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Download",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "fritzbox_value",
       "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(\"totalbytesreceived\"))) FROM /^$measurement$/ WHERE  (\"box\" =~ /^$boxtag$/) AND $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time($__interval) tz(${timezone:singlequote})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
       ],
       "target": "alias(summarize(nonNegativeDerivative(collectd.squirrel.fritzbox.bytes-totalbytesreceived, 0), '1h', 'sum'), 'download')"
      },
      {
       "alias": "Upload",
       "fields": [
        { "func": "mean", "name": "value" }
       ],
       "fill": "null",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "fritzbox_value",
       "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(\"totalbytessent\"))) FROM /^$measurement$/ WHERE  (\"box\" =~ /^$boxtag$/) AND $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time($__interval) tz(${timezone:singlequote})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "totalbytessent" }
       ],
       "target": "alias(summarize(nonNegativeDerivative(collectd.squirrel.fritzbox.bytes-totalbytessent,0),'1h','sum'),'upload')"
      }
     ]
    },
    {
     "title": "Daily Traffic",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Download",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" }
       ],
       "measurement": "fritzbox_value",
       "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(\"totalbytesreceived\"))) FROM /^$measurement$/ WHERE (box =~ /^${boxtag}$/) AND $timeFilter GROUP BY time($__interval)\n) WHERE $timeFilter GROUP BY time(1d) tz(${timezone:singlequote})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
       ]
      },
      {
       "alias": "Upload",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" }
       ],
       "measurement": "fritzbox_value",
       "query": "SELECT non_negative_difference(last(cumulative_sum)) FROM (\nSELECT cumulative_sum(non_negative_difference(last(\"totalbytessent\"))) FROM /^$measurement$/ WHERE (box =~ /^${boxtag}$/) AND $timeFilter GROUP BY time($__interval)\n)  WHERE $timeFilter GROUP BY time(1d) tz(${timezone:singlequote})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "type_instance", "operator": "=", "value": "totalbytesreceived" }
       ]
      }
     ]
    },
    {
     "title": "Total Upload since connection",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "query": "SELECT \"totalbytessent\" FROM /^$measurement$/ WHERE $timeFilter",
       "select": [
        [
         { "params": [ "totalbytessent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Download since connection",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "query": "SELECT last(\"DEV\") FROM(\nSELECT derivative(last(\"totalbytesreceived\"), $interval) as \"DEV\" FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/) AND $timeFilter GROUP BY time($interval), \"box\") WHERE \"DEV\" < 0\n",
       "select": [
        [
         { "params": [ "totalbytesreceived" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "WLAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WLAN Clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT mean(\"wlan1_associations\") AS \"2.4 GHz Clients\", mean(\"wlan2_associations\") AS \"5 GHz Clients\", mean(\"wlan3_associations\") AS \"Guest Clients\" FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "wlan1_associations" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "2.4 GHz Clients" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_associations" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "5 GHz Clients" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_associations" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Guest Clients" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "WLAN Channel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT mean(\"wlan1_associations\") AS \"2.4 GHz Clients\", mean(\"wlan2_associations\") AS \"5 GHz Clients\", mean(\"wlan3_associations\") AS \"Guest Clients\" FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "wlan1_channel" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "2.4 GHz" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_channel" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "5 GHz" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_channel" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Guest" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "WLAN Info",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "alias": "2.4 GHz Status",
       "limit": "1",
       "measurement": "/^$measurement$/",
       "query": "SELECT \"wlan1_status\" AS \"Status\", \"wlan1_802.11_standard\", \"wlan1_ssid\", \"wlan1_ssid\" FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/) AND $timeFilter LIMIT 1",
       "select": [
        [
         { "params": [ "wlan1_ssid" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Name" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan1_status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Status" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan1_802.11_standard" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Standard" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan1_channel" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Channel" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan1_associations" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Clients" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "alias": "2.4 GHz Status",
       "limit": "1",
       "measurement": "/^$measurement$/",
       "query": "SELECT \"wlan1_status\" AS \"Status\", \"wlan1_802.11_standard\", \"wlan1_ssid\", \"wlan1_ssid\" FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/) AND $timeFilter LIMIT 1",
       "select": [
        [
         { "params": [ "wlan2_ssid" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Name" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Status" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_802.11_standard" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Standard" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_channel" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Channel" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan2_associations" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Clients" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "alias": "2.4 GHz Status",
       "limit": "1",
       "measurement": "/^$measurement$/",
       "query": "SELECT \"wlan1_status\" AS \"Status\", \"wlan1_802.11_standard\", \"wlan1_ssid\", \"wlan1_ssid\" FROM /^$measurement$/ WHERE (\"box\" =~ /^$boxtag$/) AND $timeFilter LIMIT 1",
       "select": [
        [
         { "params": [ "wlan3_ssid" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Name" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Status" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_802.11_standard" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Standard" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_channel" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Channel" ], "type": "alias" }
        ],
        [
         { "params": [ "wlan3_associations" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Clients" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "System Infos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "CPU Utilization",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "cpu_utilization" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ram_usage_fixed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Fixed" ], "type": "alias" }
        ],
        [
         { "params": [ "ram_usage_dynamic" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Dynamic" ], "type": "alias" }
        ],
        [
         { "params": [ "ram_usage_free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Free" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "CPU Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "cpu_temp" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "System Energy Consumption",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "energy_consumption" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "FritzBox Info",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "external_ip" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "IPv4" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "external_ipv6" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "IPv6" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "model" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Model" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "serialnumber" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Serial" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "softwareversion" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "SW Version" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "last_auth_error" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Last Auth Error" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "myfritz_host_name" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "MyFritz Hostname" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "Connection Info",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "physicallinktype" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Link Type" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "dsl_line_length" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "DSL Line Length" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "dsl_dslam_vendor" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "DSL DSLAM Vendor" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "dsl_dslam_sw_version" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "DSL Model Version" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "dsl_line_mode" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "DSL Line Mode" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "cable_cmts_vendor" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Cable Vendor" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "cable_line_mode" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Cable Line Mode" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "cable_modem_version" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Cable Modem Version" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "cable_num_ds_channels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Cable Downstream Channels" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "cable_num_us_channels" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Cable Upstream Channels" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "connection_status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Connection Status" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "last_connection_error" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Last Connection Error" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "remote_pop" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Remote Pop" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "VPN and DynDNS Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active VPN User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 80 },
     "targets": [
      {
       "alias": "Num Users",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "vpn_user_num_active" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "VPN Infos",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 80 },
     "targets": [
      {
       "alias": "MyFritz Hostname",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "myfritz_host_name" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "alias": "VPN Type",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "vpn_type" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "alias": "VPN User Active",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "vpn_user_num_active" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "DynDNS Info",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 88 },
     "targets": [
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_domain" ], "type": "field" },
         { "params": [ "Domain" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_enabled" ], "type": "field" },
         { "params": [ "Enabled" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_mode" ], "type": "field" },
         { "params": [ "Mode" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_provider_name" ], "type": "field" },
         { "params": [ "Provider" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_status_ipv4" ], "type": "field" },
         { "params": [ "Status IPv4" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      },
      {
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "ddns_status_ipv6" ], "type": "field" },
         { "params": [ "Status IPv6" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "VPN User Overview",
     "type": "table",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 88 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "limit": "1",
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "vpn_user_active" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Active" ], "type": "alias" }
        ],
        [
         { "params": [ "vpn_user_connected" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Connected" ], "type": "alias" }
        ],
        [
         { "params": [ "vpn_user_virtual_address" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Virtual Address" ], "type": "alias" }
        ],
        [
         { "params": [ "vpn_user_remote_address" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Remote Address" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Hosts",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "uid" ], "type": "tag" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "active_hosts_name" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Name" ], "type": "alias" }
        ],
        [
         { "params": [ "active_hosts_mac" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Mac" ], "type": "alias" }
        ],
        [
         { "params": [ "active_hosts_type" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Type" ], "type": "alias" }
        ],
        [
         { "params": [ "active_hosts_port" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Port" ], "type": "alias" }
        ],
        [
         { "params": [ "active_hosts_ipv4" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "IPv4" ], "type": "alias" }
        ],
        [
         { "params": [ "active_hosts_ipv4_last_used" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*1000" ], "type": "math" },
         { "params": [ "Last seen" ], "type": "alias" }
        ],
        [
         { "params": [ "active_hosts_additional_text" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Info" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    },
    {
     "title": "Passive Hosts",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "uid" ], "type": "tag" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "passive_hosts_name" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Name" ], "type": "alias" }
        ],
        [
         { "params": [ "passive_hosts_mac" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Mac" ], "type": "alias" }
        ],
        [
         { "params": [ "passive_hosts_port" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Port" ], "type": "alias" }
        ],
        [
         { "params": [ "passive_hosts_ipv4" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "IPv4" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "box", "operator": "=~", "value": "/^$boxtag$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}